[package]
name = "app"
version = "1.0.0"
edition = "2021"
authors = ["Maxim Merkurev"]

[dependencies]
postgres = "0.19.9"
rust-ini = "0.21.1"
iron = "0.6.1"
router = "0.6.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
priority-queue = "2.1.1"